import type { Element, Root as HtmlRoot } from 'hast'
import type { Link, PhrasingContent, Root } from 'mdast'
import type { RegExpMatchObject } from 'mdast-util-find-and-replace'
import { findAndReplace as mdastFindReplace } from 'mdast-util-find-and-replace'
import { toString } from 'mdast-util-to-string'
// modified version of https://github.com/remarkjs/remark-github/blob/main/index.js
// main change: Update mentionRegex to work with rehype-citation
import fs from 'node:fs'
import path from 'node:path'
import rehypeGithubEmoji from 'rehype-github-emoji'
import { type BuildUrlValues, defaultBuildUrl } from 'remark-github'
import { visit } from 'unist-util-visit'
import type { QuartzTransformerPlugin } from '../../types/plugin'
import { isRecord } from '../../util/type-guards'

// Previously, GitHub linked `@mention` and `@mentions` to their blog post about
// mentions (<https://github.com/blog/821>).
// Since June 2019, and possibly earlier, they stopped linking those references.
const denyMention = new Set(['mention', 'mentions'])
// Denylist of SHAs that are also valid words.
//
// GitHub allows abbreviating SHAs up to 7 characters.
// These cases are ignored in text because they might just be meant as normal
// words.
// If you’d like these to link to their SHAs, use more than 7 characters.
//
// Generated by:
//
// ```sh
// egrep -i "^[a-f0-9]{7,}$" /usr/share/dict/words
// ```
//
// Added a couple forms of 6 character words in GH-20:
// <https://github.com/remarkjs/remark-github/issues/20>.
const denyHash = new Set(['acceded', 'deedeed', 'defaced', 'effaced', 'fabaceae'])
// Constants.
const minShaLength = 7
// Username may only contain alphanumeric characters or single hyphens, and
// cannot begin or end with a hyphen*.
//
// \* That is: until <https://github.com/remarkjs/remark-github/issues/13>.
const userGroup = '[\\da-z][-\\da-z]{0,38}'
const projectGroup = '(?:\\.git[\\w-]|\\.(?!git)|[\\w-])+'
const repoGroup = '(' + userGroup + ')\\/(' + projectGroup + ')'
const linkRegex = new RegExp(
  '^https?:\\/\\/github\\.com\\/' +
    repoGroup +
    '\\/(commit|compare|issues|pull)\\/([a-f\\d]+(?:\\.{3}[a-f\\d]+)?\\/?(?=[#?]|$))',
  'i',
)
const repoRegex = new RegExp('(?:^|/(?:repos/)?)' + repoGroup + '(?=\\.git|[\\/#@]|$)', 'i')
const referenceRegex = new RegExp(
  '(' + userGroup + ')(?:\\/(' + projectGroup + '))?(?:#([1-9]\\d*)|@([a-f\\d]{7,40}))',
  'gi',
)
// Only match mentions within curly braces: {@username}
const mentionRegex = new RegExp(`\\{@(${userGroup}(?:\\/${userGroup})?)\\}`, 'gi')

function getRepoFromPackage(cwd: string) {
  let pkg

  try {
    pkg = JSON.parse(String(fs.readFileSync(path.join(cwd, 'package.json'))))
  } catch {}

  const repository =
    pkg && pkg.repository
      ? // Object form.
        /* c8 ignore next 2 */
        typeof pkg.repository === 'object'
        ? pkg.repository.url
        : pkg.repository
      : ''

  return repository
}

export interface Options {
  repository?: string
  buildUrl?: (values: BuildUrlValues) => string
  mentionStrong?: boolean
  internalLinks?: string[]
  noTranslateBlock?: string[]
}

type RepositoryInfo = { project: string; user: string }

type UrlInfo = { comment: boolean; page: string; project: string; reference: string; user: string }

const defaultOptions: Options = {
  repository: 'https://github.com/animishraa05/animishraa05.github.io',
  buildUrl: defaultBuildUrl,
  mentionStrong: true,
  internalLinks: ['livingalonealone.com'],
  noTranslateBlock: ['pre', 'code'],
}

const dirTags = new Set(['div', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'ol', 'p', 'ul'])
const defaultRelations = ['nofollow']

function isElement(node: unknown): node is Element {
  return isRecord(node) && node.type === 'element' && typeof node.tagName === 'string'
}

function isString(value: unknown): value is string {
  return typeof value === 'string' && value.length > 0
}

function classList(element: Element): unknown[] {
  const className = element.properties.className
  if (Array.isArray(className)) return className
  const next: string[] = []
  element.properties.className = next
  return next
}

function shouldAddDir(element: Element): boolean {
  if (!dirTags.has(element.tagName) || !element.properties) return false
  const className = element.properties.className
  return !(Array.isArray(className) && className.includes('contains-task-list'))
}

function validateHostname(internal: string): void {
  try {
    const url = new URL('https://' + internal)
    if (url.hostname === internal) return
    throw new Error('Value `' + internal + '` is parsed as hostname `' + url.hostname + '`')
  } catch (error) {
    const exception = new Error('Expected valid hostname for URL, not `' + internal + '`')
    exception.cause = error
    throw exception
  }
}

function validateRelation(relation: string): void {
  if (!relation.includes(' ')) return
  throw new Error(
    'Expected valid `rel` value, without space (note: use arrays to pass multiple values)',
  )
}

function isKnownHostname(hostname: string, internals: string[]): boolean {
  for (const internal of internals) {
    if (hostname === internal || hostname.endsWith('.' + internal)) return true
  }
  return false
}

function addExternalRelations(
  element: Element,
  internals: string[],
  defaultHostname: string,
): void {
  if (element.tagName !== 'a') return
  const href = element.properties.href
  if (typeof href !== 'string') return

  let url: URL | undefined
  try {
    url = new URL(href, 'https://' + defaultHostname)
  } catch {}

  if (!url || !url.hostname || isKnownHostname(url.hostname, internals)) return

  const rel = Array.isArray(element.properties.rel) ? element.properties.rel : []
  for (const relation of defaultRelations) {
    if (!rel.includes(relation)) rel.push(relation)
  }
  element.properties.rel = rel
}

function shortenGithubLink(element: Element): void {
  if (element.tagName !== 'a') return
  const href = element.properties.href
  if (typeof href !== 'string') return

  const githubMatch = href.match(/^https:\/\/github\.com\/([^/]+)\/([^/\s#]+)/)
  if (!githubMatch || toString(element) !== href) return

  element.children = [{ type: 'text', value: `${githubMatch[1]}/${githubMatch[2]}` }]
}

export const GitHub: QuartzTransformerPlugin<Partial<Options>> = userOpts => {
  const opts = { ...defaultOptions, ...userOpts }
  const buildUrl = opts.buildUrl || defaultBuildUrl

  return {
    name: 'GitHub',
    markdownPlugins() {
      return [
        () => {
          return (tree: Root, file) => {
            const repository = opts.repository || getRepoFromPackage(file.cwd)

            if (!repository) {
              throw new Error('Unexpected missing `repository` in `options`')
            }

            // Parse the URL: See the tests for all possible kinds.
            const repositoryMatch = repoRegex.exec(repository)

            if (!repositoryMatch) {
              throw new Error(
                'Unexpected invalid `repository`, expected for example `user/project`',
              )
            }

            const repositoryInfo: RepositoryInfo = {
              project: repositoryMatch[2],
              user: repositoryMatch[1],
            }
            // TODO: add support for mentions back here.
            mdastFindReplace(
              tree,
              [
                //@ts-ignore
                [referenceRegex, replaceReference],
                //@ts-ignore
                [mentionRegex, replaceMention],
                [/(?:#|\bgh-)([1-9]\d*)/gi, replaceIssue],
                [/\b([a-f\d]{7,40})\.{3}([a-f\d]{7,40})\b/gi, replaceHashRange],
                [/\b[a-f\d]{7,40}\b/gi, replaceHash],
              ],
              { ignore: ['link', 'linkReference'] },
            )

            visit(tree, 'link', function (node) {
              const link = parse(node)

              if (!link) {
                return
              }

              const comment = link.comment ? ' (comment)' : ''
              // NOTE: Deviate from the original implementation where
              // we always format the base to user/project
              let base: string = link.user + '/' + link.project

              const children: PhrasingContent[] = []

              if (link.page === 'issues' || link.page === 'pull') {
                base += '#'
                children.push({ type: 'text', value: base + link.reference + comment })
              } else {
                if (base) {
                  children.push({ type: 'text', value: base + '@' })
                }

                children.push({ type: 'inlineCode', value: link.reference })

                if (link.comment) {
                  children.push({ type: 'text', value: comment })
                }
              }

              node.children = children
            })

            /**
             * @type {ReplaceFunction}
             * Note that our implementation is a bit different where we will encapsulate
             * `{@mentions}` to include users tag.
             */
            function replaceMention(value: string, username: string, match: RegExpMatchObject) {
              if (match === undefined) return false
              if (
                /[\w`]/.test(match.input.charAt(match.index - 1)) ||
                /[/\w`]/.test(match.input.charAt(match.index + value.length)) ||
                denyMention.has(username)
              ) {
                return false
              }

              const url = buildUrl({ type: 'mention', user: username })

              if (!url) return false

              let node: PhrasingContent = { type: 'text', value: '@' + username }

              if (opts.mentionStrong !== false) {
                node = { type: 'strong', children: [node] }
              }

              return { type: 'link', title: null, url, children: [node] }
            }

            /**
             * @type {ReplaceFunction}
             */
            function replaceIssue(value: string, no: string, match: RegExpMatchObject) {
              if (
                /\w/.test(match.input.charAt(match.index - 1)) ||
                /\w/.test(match.input.charAt(match.index + value.length))
              ) {
                return false
              }

              const url = buildUrl({ no, type: 'issue', ...repositoryInfo })

              return url
                ? { type: 'link', title: null, url, children: [{ type: 'text', value }] }
                : false
            }

            /**
             * @type {ReplaceFunction}
             */
            function replaceHashRange(
              value: string,
              a: string,
              b: string,
              match: RegExpMatchObject,
            ) {
              if (
                /[^\t\n\r (@[{]/.test(match.input.charAt(match.index - 1)) ||
                /\w/.test(match.input.charAt(match.index + value.length)) ||
                denyHash.has(value)
              ) {
                return false
              }

              const url = buildUrl({ base: a, compare: b, type: 'compare', ...repositoryInfo })

              return url
                ? {
                    type: 'link',
                    title: null,
                    url,
                    children: [{ type: 'inlineCode', value: abbr(a) + '...' + abbr(b) }],
                  }
                : false
            }

            /**
             * @type {ReplaceFunction}
             */
            function replaceHash(value: string, match: RegExpMatchObject) {
              if (
                /[^\t\n\r (@[{.]/.test(match.input.charAt(match.index - 1)) ||
                // For some weird reason GH does link two dots, but not one 🤷‍♂️
                (match.input.charAt(match.index - 1) === '.' &&
                  match.input.charAt(match.index - 2) !== '.') ||
                /\w/.test(match.input.charAt(match.index + value.length)) ||
                denyHash.has(value)
              ) {
                return false
              }

              const url = buildUrl({ hash: value, type: 'commit', ...repositoryInfo })

              return url
                ? {
                    type: 'link',
                    title: null,
                    url,
                    children: [{ type: 'inlineCode', value: abbr(value) }],
                  }
                : false
            }

            /**
             * @type {ReplaceFunction}
             */
            function replaceReference(
              $0: string,
              user: string,
              specificProject: string,
              no: string,
              hash: string,
              match: RegExpMatchObject,
            ) {
              if (
                /[^\t\n\r (@[{]/.test(match.input.charAt(match.index - 1)) ||
                /\w/.test(match.input.charAt(match.index + $0.length))
              ) {
                return false
              }

              const project = specificProject || repositoryInfo.project
              const values: BuildUrlValues = no
                ? { no, project, type: 'issue', user }
                : { hash, project, type: 'commit', user }
              const url = buildUrl(values)

              if (!url) return false

              const nodes: PhrasingContent[] = []
              let value = ''

              if (project !== repositoryInfo.project) {
                value += user + '/' + project
              } else if (user !== repositoryInfo.user) {
                value += user
              }

              if (no) {
                value += '#' + no
              } else {
                value += '@'
                nodes.push({ type: 'inlineCode', value: abbr(hash) })
              }

              nodes.unshift({ type: 'text', value })

              return { type: 'link', title: null, url, children: nodes }
            }
          }
        },
      ]
    },
    htmlPlugins({ cfg }) {
      const internals = [
        'github.com',
        cfg.configuration.baseUrl,
        ...(opts.internalLinks ?? []),
      ].filter(isString)
      const noTranslateBlock = new Set(opts.noTranslateBlock ?? [])

      for (const internal of internals) validateHostname(internal)
      for (const relation of defaultRelations) validateRelation(relation)

      const defaultHostname = internals[0]

      return [
        () => (tree: HtmlRoot) => {
          visit(tree, node => {
            if (!isElement(node)) return
            if (shouldAddDir(node)) node.properties.dir = 'auto'
            if (noTranslateBlock.has(node.tagName)) {
              const classes = classList(node)
              if (!classes.includes('notranslate')) classes.push('notranslate')
            }
            addExternalRelations(node, internals, defaultHostname)
            shortenGithubLink(node)
          })
        },
        rehypeGithubEmoji,
      ]
    },
  }
}

/**
 * Abbreviate a SHA.
 */
function abbr(sha: string): string {
  return sha.slice(0, minShaLength)
}

/**
 * Parse a link and determine whether it links to GitHub.
 */
function parse(node: Link): UrlInfo | undefined {
  const match = linkRegex.exec(node.url)

  if (
    // Not a proper URL.
    !match ||
    // Looks like formatting.
    node.children.length !== 1 ||
    node.children[0].type !== 'text' ||
    toString(node) !== node.url ||
    // SHAs can be min 4, max 40 characters.
    (match[3] === 'commit' && (match[4].length < 4 || match[4].length > 40)) ||
    // SHAs can be min 4, max 40 characters.
    (match[3] === 'compare' && !/^[a-f\d]{4,40}\.{3}[a-f\d]{4,40}$/.test(match[4])) ||
    // Issues / PRs are decimal only.
    ((match[3] === 'issues' || match[3] === 'pull') && /[a-f]/i.test(match[4])) ||
    // Projects can be at most 99 characters.
    match[2].length >= 100
  ) {
    return
  }

  let reference = match[4]

  if (match[3] === 'compare') {
    const [base, compare] = reference.split('...')
    reference = abbr(base) + '...' + abbr(compare)
  } else {
    reference = abbr(reference)
  }

  return {
    comment: node.url.charAt(match[0].length) === '#' && match[0].length + 1 < node.url.length,
    page: match[3],
    project: match[2],
    reference,
    user: match[1],
  }
}
